title: NRF24LE1
description: Ferramentas para programação do módulo NRF24LE1.
show_downloads: true
remote_theme: mmistakes/skinny-bones-jekyll
github:
  zip_url: https://github.com/italogfernandes/nrf24le1/releases/
  another_url: https://github.com/italogfernandes/nrf24le1/releases
